spring:
  application:
    name: ai-code-helper
server:
  port: 8081
  servlet:
    context-path: /api
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: 1
      embedding-model:
        model-name: text-embedding-v4
        api-key: 1
      streaming-chat-model:
        model-name: qwen-max
        api-key: 1
bigmodel:
  api-key: 1

